# -*- coding: utf-8 -*-
"""Punto_4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RyLPKr76XsXXICfinr2kBoVhA43Up0iB

##**Punto 4**
"""

#Para calcular el tiempo cuando un valor es ingresado por el usuario

import time
def fiboRecursivo(n : int )-> int:
  if n <=1:
    # caso base
    return 1
  else:
    # condicion
    return fiboRecursivo(n-1)+fiboRecursivo(n-2)

if __name__ == "__main__":
  start_time = time.time()
  num = int(input("Ingrese numero: "))
  serieFibo = fiboRecursivo(num)
  print("La serie de Fibonacci hasta " + str(num) + " es " + str(serieFibo))
  end_time = time.time()

  timer = end_time - start_time
  print("El tiempo que se demoró el programa fue de: " + str(timer))

#Para calcular desde que número de la serie la diferencia de tiempo se vuelve sorgnificativa

import time

bandera = True
i : int = 1

while bandera == True:

  def fiboRecursivo(n : int )-> int:
   if n <=1:
     # caso base
    return 1
   else:
    # condicion
    return fiboRecursivo(n-1)+fiboRecursivo(n-2)

  if __name__ == "__main__":
    start_time = time.time()
    num = i
    serieFibo = fiboRecursivo(num)
    end_time = time.time()
    timer = end_time - start_time

  if timer > 5.0: #necesitamos agilidad
    break
  else:
    i=i+1
print("La serie de Fibonacci hasta " + str(num) + " es " + str(serieFibo))
print("A partir de este numero se debe considerar un tiempo considerable superior a 5seg")
print("Su tiempo de ejecución hasta aquí fue de : " +str(timer))